/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUtilisateursRouteImport } from './routes/_app.utilisateurs'
import { Route as AppRelanceRouteImport } from './routes/_app.relance'
import { Route as AppReclamationsRouteImport } from './routes/_app.reclamations'
import { Route as AppQualificationRouteImport } from './routes/_app.qualification'
import { Route as AppDesignRouteImport } from './routes/_app.design'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBaseConnaissanceRouteImport } from './routes/_app.base-connaissance'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUtilisateursRoute = AppUtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => AppRoute,
} as any)
const AppRelanceRoute = AppRelanceRouteImport.update({
  id: '/relance',
  path: '/relance',
  getParentRoute: () => AppRoute,
} as any)
const AppReclamationsRoute = AppReclamationsRouteImport.update({
  id: '/reclamations',
  path: '/reclamations',
  getParentRoute: () => AppRoute,
} as any)
const AppQualificationRoute = AppQualificationRouteImport.update({
  id: '/qualification',
  path: '/qualification',
  getParentRoute: () => AppRoute,
} as any)
const AppDesignRoute = AppDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBaseConnaissanceRoute = AppBaseConnaissanceRouteImport.update({
  id: '/base-connaissance',
  path: '/base-connaissance',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/base-connaissance': typeof AppBaseConnaissanceRoute
  '/dashboard': typeof AppDashboardRoute
  '/design': typeof AppDesignRoute
  '/qualification': typeof AppQualificationRoute
  '/reclamations': typeof AppReclamationsRoute
  '/relance': typeof AppRelanceRoute
  '/utilisateurs': typeof AppUtilisateursRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/base-connaissance': typeof AppBaseConnaissanceRoute
  '/dashboard': typeof AppDashboardRoute
  '/design': typeof AppDesignRoute
  '/qualification': typeof AppQualificationRoute
  '/reclamations': typeof AppReclamationsRoute
  '/relance': typeof AppRelanceRoute
  '/utilisateurs': typeof AppUtilisateursRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/base-connaissance': typeof AppBaseConnaissanceRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/design': typeof AppDesignRoute
  '/_app/qualification': typeof AppQualificationRoute
  '/_app/reclamations': typeof AppReclamationsRoute
  '/_app/relance': typeof AppRelanceRoute
  '/_app/utilisateurs': typeof AppUtilisateursRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/base-connaissance'
    | '/dashboard'
    | '/design'
    | '/qualification'
    | '/reclamations'
    | '/relance'
    | '/utilisateurs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/base-connaissance'
    | '/dashboard'
    | '/design'
    | '/qualification'
    | '/reclamations'
    | '/relance'
    | '/utilisateurs'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/base-connaissance'
    | '/_app/dashboard'
    | '/_app/design'
    | '/_app/qualification'
    | '/_app/reclamations'
    | '/_app/relance'
    | '/_app/utilisateurs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/utilisateurs': {
      id: '/_app/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/utilisateurs'
      preLoaderRoute: typeof AppUtilisateursRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relance': {
      id: '/_app/relance'
      path: '/relance'
      fullPath: '/relance'
      preLoaderRoute: typeof AppRelanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reclamations': {
      id: '/_app/reclamations'
      path: '/reclamations'
      fullPath: '/reclamations'
      preLoaderRoute: typeof AppReclamationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/qualification': {
      id: '/_app/qualification'
      path: '/qualification'
      fullPath: '/qualification'
      preLoaderRoute: typeof AppQualificationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/design': {
      id: '/_app/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof AppDesignRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/base-connaissance': {
      id: '/_app/base-connaissance'
      path: '/base-connaissance'
      fullPath: '/base-connaissance'
      preLoaderRoute: typeof AppBaseConnaissanceRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBaseConnaissanceRoute: typeof AppBaseConnaissanceRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDesignRoute: typeof AppDesignRoute
  AppQualificationRoute: typeof AppQualificationRoute
  AppReclamationsRoute: typeof AppReclamationsRoute
  AppRelanceRoute: typeof AppRelanceRoute
  AppUtilisateursRoute: typeof AppUtilisateursRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBaseConnaissanceRoute: AppBaseConnaissanceRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDesignRoute: AppDesignRoute,
  AppQualificationRoute: AppQualificationRoute,
  AppReclamationsRoute: AppReclamationsRoute,
  AppRelanceRoute: AppRelanceRoute,
  AppUtilisateursRoute: AppUtilisateursRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
